// File is autogenerated with `dub spasm:webidl -- --bindgen`
import * as bindings from './bindings.js';
import * as spa from './spa.js';
import * as spasm from './spasm.js';
import * as wasi from './wasi.js';
const modules = [bindings, spa, spasm, wasi];
export { spasm, modules }